// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['API_KEY_ANDROID'] ?? 'API_KEY NOT FOUND',
    appId: dotenv.env['APP_ID_ANDROID'] ?? 'APP_ID NOT FOUND',
    messagingSenderId: dotenv.env['MESSAGING_ID'] ?? 'MESSAGING_ID NOT FOUND',
    projectId: dotenv.env['PROJECT_ID'] ?? 'PROJECT_ID NOT FOUND',
    storageBucket: dotenv.env['STTORAGE_ID'] ?? 'STTORAGE_ID NOT FOUND',
    databaseURL: dotenv.env['DATABASE_URL'] ?? 'DATABASE_URL NOT FOUND',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['API_KEY_IOS'] ?? 'API_KEY NOT FOUND',
    appId: dotenv.env['APP_ID_IOS'] ?? 'APP_ID NOT FOUND',
    messagingSenderId: dotenv.env['MESSAGING_ID'] ?? 'MESSAGING_ID NOT FOUND',
    projectId: dotenv.env['PROJECT_ID'] ?? 'PROJECT_ID NOT FOUND',
    storageBucket: dotenv.env['STTORAGE_ID'] ?? 'STTORAGE_ID NOT FOUND',
    databaseURL: dotenv.env['DATABASE_URL'] ?? 'DATABASE_URL NOT FOUND',
    iosBundleId: dotenv.env['IOS_BUNDLER'] ?? 'IOS_BUNDLER NOT FOUND',
  );

}